From golang:latest as base

# Install tools required for project
# Run `docker build --no-cache .` to update dependencies
RUN apk add --no-cache git
RUN go get github.com/golang/dep/cmd/dep

COPY . /go/src/go-contacts

WORKDIR /go/src/go-contacts

# TO install dependency packages
RUN go mod tidy

# to build the executable
RUN go build .

# container port
EXPOSE 8080

ENTRYPOINT ["./contacts"]