From golang:latest as base

# Install tools required for project
# Run `docker build --no-cache .` to update dependencies
RUN apk add --no-cache git
RUN go get github.com/golang/dep/cmd/dep

COPY . /go/src/go-contacts

WORKDIR /go/src/go-contacts

RUN go mod tidy

RUN go build .

EXPOSE 8080

ENTRYPOINT ["./contacts"]